# Generated by Django 4.0.1 on 2022-01-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=50)),
                ('continent_code', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
                ('region_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_eu', models.BooleanField(default=True)),
            ],
        ),
    ]
